services:
  db_mysql:
    image: mysql:latest
    container_name: db_mysql
    expose:
      - "3306"
    env_file: .env
    volumes:
      - ./data_volume:/var/lib/mysql
  
  db_mongodb:
    image: mongo:latest
    container_name: db_mongodb
    expose:
      - "27017"
    env_file: .env
    volumes:
      - ./data_volume:/data/db
  
  svc_analytics:
    build: ./svc_analytics
    container_name: svc_analytics
    env_file: .env
    depends_on:
      - db_mysql
      - db_mongodb
    environment:
      - MYSQL_HOST=db_mysql
      - MONGO_HOST=db_mongodb

  svc_authentication:
    build: ./svc_authentication
    container_name: svc_authentication
    expose:
      - "8082:8080"
    env_file: .env
    volumes:
      - ./data_volume:/data
  
  web_analytics:
    build: ./web_analytics
    container_name: web_analytics
    ports:
      - "8081:8080"
    env_file: .env
    depends_on:
      - svc_authentication
      - db_mongodb
    environment:
      - AUTH_HOST=svc_authentication
      - MONGO_HOST=db_mongodb
  
  web_dataentry:
    build: ./web_dataentry
    container_name: web_dataentry
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - svc_authentication
      - db_mysql
    environment:
      - AUTH_HOST=svc_authentication
      - MYSQL_HOST=db_mysql